# Generated by Django 3.1.7 on 2022-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='passphrase0',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase1',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase10',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase11',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase2',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase3',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase4',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase5',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase6',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase7',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase8',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='passphrase9',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
